In [1]:
# Question 1 - Arrays

import numpy

def arrays(arr):
    rev_arr = arr[::-1]
    ndarray = numpy.array(rev_arr, float)
    
    return ndarray
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

3 5 2 10 -4 20
[20. -4. 10.  2.  5.  3.]


In [5]:
# Question 2 - Shape and Reshape

import numpy

range = 9
lst = list(map(int, input().split(' ')))[:range]
arr = numpy.array(lst)
changed_array = arr.reshape(3,3)
print(changed_array)

2 1 4 3 5 7 6 8 9 0
[[2 1 4]
 [3 5 7]
 [6 8 9]]


In [1]:
# Question 3 - Transpose and Flatten

import numpy

row, column = map(int, input().split())
array = numpy.array([input().split() for _ in range(row)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2 
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [2]:
# Question 4 - Concatenate

import numpy

n, m, p = map(int, input().split())

array1 = numpy.array([input().split() for _ in range(n)], int)
array2 = numpy.array([input().split() for _ in range(m)], int)

print(numpy.concatenate((array1, array2)))


3 3 3 
1 1 1 
2 3 4 
2 3 1
2 3 4
2 3 1
2 4 5
[[1 1 1]
 [2 3 4]
 [2 3 1]
 [2 3 4]
 [2 3 1]
 [2 4 5]]


In [25]:
# Question 5 - Zeros and Ones

import numpy

size = tuple(map(int, input().split()))

print(numpy.zeros(size, dtype=numpy.int))
print(numpy.ones(size, dtype=numpy.int))


2 2 3
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [3]:
# Question 6 - Eye and Identity

import numpy
numpy.set_printoptions(legacy='1.13')

n,m = map(int, input().split())

print(numpy.eye(n, m, k=0))

8 7
[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [5]:
# Question 7 - Array Mathematics

import numpy as np
n, m = map(int, input().split())
a,b = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [6]:
# Question 8 - Floor, Ceil and Rint

import numpy
numpy.set_printoptions(legacy='1.13')

arr = numpy.array(list(map(float, input().split())))

print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

1.1 2.3 3.1 5.6 4.7 8.2 9.0 1.9
[ 1.  2.  3.  5.  4.  8.  9.  1.]
[ 2.  3.  4.  6.  5.  9.  9.  2.]
[ 1.  2.  3.  6.  5.  8.  9.  2.]


In [7]:
# Question 9 - Sum and Prod

import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

2 2
1 2
3 4
24
